/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waterflower_jnidemo_JNIUtils */

#ifndef _Included_com_waterflower_jnidemo_JNIUtils
#define _Included_com_waterflower_jnidemo_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waterflower_jnidemo_JNIUtils
 * Method:    getStrFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_waterflower_jnidemo_JNIUtils_getStrFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
